### ISSUE TITLE
پورت

### ISSUE THREAD

**Issue by l3lack-eyes** [TheyCallMeSecond/config-examples#1]
خسته نباشید . کانفیگ ها چه پورت هایی رو اشغال میکنن . Xui نصب دارم نمیخوام stop بخوره

**Comment by TheyCallMeSecond** [comment]
خودتون تعیین می کنین

**Comment by l3lack-eyes** [comment]
ممنون

**Comment by l3lack-eyes** [comment]
mkdir: cannot create directory ‘/root/cert’: File exists
روی پورت باز زدم این ارور رو داد مشکل از کجاست یوزرم هم روت هست

**Comment by TheyCallMeSecond** [comment]
روی سرورتون از قبل این فولدر رو داشتید
