### ISSUE TITLE
Naive

### ISSUE THREAD

**Issue by misagh72** [TheyCallMeSecond/config-examples#11]
سلام میشه پروتکل Navie رو هم اضافه کنید 
ممنون از اسکریپت خوبتون

**Comment by TheyCallMeSecond** [comment]
سلام
من تجربه استفاده ازشو نداشتم.خوبه؟ اگه خوبه واضافش میکنم

**Comment by misagh72** [comment]
> سلام من تجربه استفاده ازشو نداشتم.خوبه؟ اگه خوبه واضافش میکنم

اره خوبه / روی همراه تست کردم

**Comment by TheyCallMeSecond** [comment]
udp/quick یا tcp/https?
کدوم بقیه؟

**Comment by misagh72** [comment]
منظورم tuicو هسیتریا۲  اونا بدون دامنه کار میکنن

**Comment by TheyCallMeSecond** [comment]
TUIC و HY2 بدون دامنه کار میکنن
به هر حال کدهای naive رو آماده کردم.خودم تستش میکنم اگه اوکی بود آپدیت میکنم اسکریپت رو

**Comment by misagh72** [comment]
می‌دونم اونا بدون دامنه کار می کنن
من naive رو گفتم بدون دامنه کار نمیکنه باید دامنه داشته باشی حتما

**Comment by misagh72** [comment]
تست کردین ؟

**Comment by TheyCallMeSecond** [comment]
اضافه شد
