### ISSUE TITLE
Add Users

### ISSUE THREAD

**Issue by NoRRt** [TheyCallMeSecond/config-examples#12]
سلام خسته نباشید - امکانش هست گزینه اضافه کردن یوزر (Add User) رو به تمامی پروتکل هت اضافه کنید .
مثال ( برای HY2 چند تا یوزر یا همون  برای چند نفر یوزر بسازی )

1:  Install Hysteria2
**2:  Add User / Del User**
2:  Modify Hysteria2 Config
3:  Show Hysteria2 Config
4:  Enable/Disable WARP on Hysteria2
5:  Uninstall Hysteria2

**Comment by TheyCallMeSecond** [comment]
کدهاش رو آماده کردم ولی هنوز تست نکردم رو سرور

**Comment by TheyCallMeSecond** [comment]
اضافه شد
