### ISSUE TITLE
مشکل بعد از نصب warp

### ISSUE THREAD

**Issue by miladj3** [TheyCallMeSecond/config-examples#14]
قبل از نصب warp همه چیز اوکی بود. اما بعد از اینکه warp رو نصب کردم بهم توی همه پروتوکل ها این اررور رو نمایش میده

Failed:: decode config: unknown outbound type

**Comment by TheyCallMeSecond** [comment]
![231102_13h50m20s_screenshot](https://github.com/TheyCallMeSecond/config-examples/assets/73380906/0cb21827-0d19-42a6-8eb9-10f3b60f1875)

این گزینه رو انتخاب کردین واسه اولین بار؟

**Comment by miladj3** [comment]
این گزینه رو ندیدم اصلا.
