### ISSUE TITLE
Allow Insecure is enabled when importing the config into Nekobox(hysteria)

### ISSUE THREAD

**Issue by mfat** [TheyCallMeSecond/config-examples#17]
Is this the intended behavior? Is it safe?

**Comment by TheyCallMeSecond** [comment]
Absolutely... the protocol itself encrypts the connection...but if you want secure connection you can set the certificate in nekobox (it is in protocol's config folder, "server.crt")

**Comment by mfat** [comment]
Thanks. 
@hawshemi says this causes the server's IP to be "graylisted".

**Comment by hawshemi** [comment]
`allowinsecure=true` will increase the risk of the IP address going to the graylist. (especially for MCI operators)

**Comment by TheyCallMeSecond** [comment]
> `allowinsecure=true` will increase the risk of the IP address going to the graylist. (especially for MCI operators)

are you sure? its just a certification check between server and client and no middleman involved...if using hysteria on 443 port without obfs its completely like a normal quick connection
