### ISSUE TITLE
Choosing between tcp and udp format in hysteria and tuic configurations

### ISSUE THREAD

**Issue by itsmostafa75** [TheyCallMeSecond/config-examples#19]
اگر براتون مقدور هست لطفا من رو در این مورد زیر،راهنمایی بفرمایید.

هیستریا ۲،هم udp هم tcp رو ساپورت میکنه.
بر روی اکثر شرکتهای adsl، پروتکل udp مسدود هستش.
من برای ساخت کانفیگ هیستریا۲ و توییک،از اسکریپت شما استفاده میکنم که بصورت پیشفرض،کانفگیهای ساخته شده،از udp استفاده میکنند و به همین خاطر کانفیگهای ساخته شده بر روی adsl، فعال نیستن.

چگونه میتونم در اسکریپت شما،فایل تنظیمات مربوطه رو پیدا کنم و به جای استفاده از udp،حالت tcp را انتخاب کنم؟

**Comment by TheyCallMeSecond** [comment]
سلام
مسیر کانفیگ هیستریا:
/etc/hysteria2/server.json
مسیر کانفیگ تویک:
/etc/tuic/server.json

**Comment by itsmostafa75** [comment]
مرسی از شما
من برای کانفیگ توییک،مسیری که کفتید رو با ویرایشگر nano باز کردم تا ادیت کنم و نتیجه زیر برام نمایش داده شد.برای اینکه udp رو سوییچ کنم به tcp،باید کدوم قسمت رو در تصوبر تغییر بدم؟عذرمیخوام من کاربر معمولی هتسم و دانش اندکی دارم،به همین خاطر سوال میکنم.بازم مرسی از شما
![PicsArt_23-11-18_02-30-57-987](https://github.com/TheyCallMeSecond/config-examples/assets/122526754/fa88d304-716b-49fc-94cf-2f006c7e1861)

**Comment by TheyCallMeSecond** [comment]
طبق داکیومنتیشن سینگ باکس راهی برای استفاده از tcp به جای udp وجود نداره
[http://sing-box.sagernet.org/configuration/inbound/hysteria2/](url)
[http://sing-box.sagernet.org/configuration/inbound/tuic/](url)
ولی خوده هسته هیستریا2 ظاهرا این قابلیت رو داره : 
[https://hysteria.network/docs/advanced/Full-Server-Config/#udp](url)

**Comment by itsmostafa75** [comment]
بسیار ممنونم از شما
هیستریا رو نیز در سرور چک‌کردم که نتیحه زیر مشاهده شد و انگار جایی برای تغییر udp به tcp وجود نداره.
تغییر در خود هسته هیستریا برای سوییچ از udp به tcp هم فک کنم تخصصی باشه و من نتونم.واقعا هیچ راهی برای اجرای توییک و هیستریا بر روی adsl نیست؟چون بعضی کانفیگ فروشها،کانفیگ های هیستریا و توییکشون روی adsl فعال هستش.کاش میشد ترفند این افراد رو متوجه شد.بازم ممنون از وقتی که گذاشتین 🌹

**Comment by TheyCallMeSecond** [comment]
mitunin az in scriptam estefade konin vase nasbe hysteria2 ba hasteye khode hysteria :

```bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/TheyCallMeSecond/config-examples/main/Hysteria/HY2-installer.sh)"
```

faghat be domain niaz dare

**Comment by itsmostafa75** [comment]
آهان مرسی از شما 🌹

**Comment by misagh72** [comment]
> آهان مرسی از شما 🌹

دوست عزیز tuic هستریا اینا بر اساس udp کار میکنن نمیتونید تغییر بدین به Tcp برای استفاده tcp بهتره ریلیتی استفاده کنید

**Comment by itsmostafa75** [comment]
ممنونم از شما اما یکی از دوستان برنامه نویس این مورد رو پینسهاد دادن
و اینکه چند کانفیگ فروش هم خودم تست کردم،روی اپراتوری که udp بسته است، توییک و هیستریا ساخته بودن و کار میکرد‌.
پس شاید روش دیگه ای دارن.مرسی ار شما 🌹
