### ISSUE TITLE
ShadowTLS not working

### ISSUE THREAD

**Issue by mfat** [TheyCallMeSecond/config-examples#2]
I tried different ports and SNIs but shadowTLS won't work.
Here are the SNIs I tried: speedtest.net, telewebion.com

**Comment by TheyCallMeSecond** [comment]
The Sni should not be an internal site like telewebion...try speedtest with "www" --> www.speedtest.net

**Comment by mfat** [comment]
Tried www.speedtest.net. No luck.
Hysteria on the same server works very well on another port.

**Comment by TheyCallMeSecond** [comment]
use this tool
