### ISSUE TITLE
Certificate Domain (self-signed)

### ISSUE THREAD

**Issue by NoRRt** [TheyCallMeSecond/config-examples#20]
سلام یه نگاهی به این بندازین و ی تستی کنین 
`  read -p "Please enter the domain name to use for the self-signed certificate （Default bing.com）: " user_domain`

[Certificate Domain (self-signed).txt](https://github.com/TheyCallMeSecond/config-examples/files/13467143/Certificate.Domain.self-signed.txt)

**Comment by TheyCallMeSecond** [comment]
? متوجه نمیشم.چیو تست کنم؟ این یه فانکشنه برای گرفتنه self-signed  سرتیفیکیت...
