### ISSUE TITLE
Unsupported OS

### ISSUE THREAD

**Issue by sarabbafrani** [TheyCallMeSecond/config-examples#26]
سلام من قبلا روی debian minimal ستاپ کردم و استفاده کردم
الان هر کاری میکنم با دستور curl 
خطای Unsupported OS میده

**Comment by sarabbafrani** [comment]
debian 12 also

**Comment by TheyCallMeSecond** [comment]
bash <(curl -fsSL https://raw.githubusercontent.com/TheyCallMeSecond/config-examples/main/Sing-Box_Config_Installer/TUI-Menu.sh)
