### ISSUE TITLE
Hysteria v2.2.4

### ISSUE THREAD

**Issue by amin2plus** [TheyCallMeSecond/config-examples#33]
سلام، با تشکر فراوان بابت این پنل فوق الغاده،
آیا امکانش هست نسخه هیستریا رو بروز کنید؟

https://github.com/apernet/hysteria/releases/tag/app%2Fv2.2.4

اگر خودمون این کار رو میتونیم انجام بدیم اگر توضیح بدین بسیار ممنونتون میشم

**Comment by TheyCallMeSecond** [comment]
سلام.خواهش میکنم 
همه‌ی پروتکل‌ها با هسته‌ی سینگ-باکس اجرا میشن
برای آپدیت هسته سینک-باکس هم میتونین از گزینه‌ی آپدیت داخل پنل استقاده کنین

**Comment by amin2plus** [comment]
فهمیدم، با تشکر
