### ISSUE TITLE
No QR code

### ISSUE THREAD

**Issue by mfat** [TheyCallMeSecond/config-examples#4]
I'm getting no qr codes, only links. The package qrencode is installed.

**Comment by TheyCallMeSecond** [comment]
it works fine
![231001_17h32m28s_screenshot](https://github.com/TheyCallMeSecond/config-examples/assets/73380906/c57d86a3-d98c-40d0-bd32-23f5427be3db)

**Comment by TheyCallMeSecond** [comment]
Only shadowtls doesn't have QR

**Comment by mfat** [comment]
Yeah i used it for ShadowTLS. Thanks much.
