### ISSUE TITLE
بهترین پنل تنها یک درخواست

### ISSUE THREAD

**Issue by ahmadyaninavid** [TheyCallMeSecond/config-examples#8]
سلام و عرض ادب 
خیلی خسته نباشید، اسکریپتی که طراحی کردین فوق العادس، اگر مقدور باشه برای پروتکل ها مخصوصا هیستریا 2 اکانتیگ اوکی اوکی کنین فوق العادس

**Comment by TheyCallMeSecond** [comment]
سلام
خواهش می کنم...متاسفانه امکان پذیر نیست به دو دلیل : 1-این اسکریپت برای استفاده شخصی طراحی شده. 2-هسته سینگ باکس بر خلاف هسته xray قابلیت api نداره...یعنی نمیشه براش یوزرهای مختلف با قابلیت محدودیت زمانی و ترافیک تعریف کرد
