### ISSUE TITLE
Single-select or multi-select protocols

### ISSUE THREAD

**Issue by NoRRt** [TheyCallMeSecond/config-examples#9]
سلام - شما می تونید از این پروژه جدید  نمونه برداری کنید برای Sing box
کار های جالبی میکنه .
[Single-select or multi-select protocols.](https://github.com/fscarmen/sing-box/commit/898ebf9e76dd0fe18659254dd3a65a0b0a1025e2)

**Comment by TheyCallMeSecond** [comment]
کدوم قابلیت مد نظرتونه؟ کد رو بررسی کردم چیز خاصی برای اضافه کردن پیدا نکردم

**Comment by NoRRt** [comment]
ببخشید یاداوری می کنم مثل اینکه آقای [hawshemi](https://github.com/hawshemi)  پروژه بهینه سازی  Vps رو بروز رسانی کردین . اگه امکانش هست شما اعمال کنید

**Comment by TheyCallMeSecond** [comment]
> همین که با انتخاب یک گزینه میشه چند پروتکل رو دریافت کرد . ( البته اینم یه آپشنه)

من ترجیح میدم یوزر خودش انتخاب کنه چیو میخواد نصب کنه

**Comment by TheyCallMeSecond** [comment]
> ببخشید یاداوری می کنم مثل اینکه آقای [hawshemi](https://github.com/hawshemi) پروژه بهینه سازی Vps رو بروز رسانی کردین . اگه امکانش هست شما اعمال کنید

در آپدیت بعدی اسکریپت اپتیمایزر رو هم آپدیت میکنم (با یه سری تغییرات)

**Comment by TheyCallMeSecond** [comment]
آپدیت شد
